models/Reserve.php
<?php

namespace app\models;

use Yii;
use app\models\Service;
use app\helper\TextOnImage;
use app\models\Sector;
use app\helper\Helper;

/**
 * This is the model class for table "reserve".
 *
 * @property integer $id
 * @property integer $service_id
 * @property string $date_time
 * @property resource $image
 */
class Reserve extends \yii\db\ActiveRecord {

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'reserve';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['service_id'], 'integer'],
            [['date_time'], 'safe'],
            [['image'], 'string'],
            [['service_id', 'date_time'], 'required'],
        ];
    }

    public function writeText() {
        $service = $this->service;

        if (isset($service, $service->name, $service->image)) {
            $file = $service->image;
            $ttfImg = new TextOnImage($file, true);

            $ttfImg->ttfFontDir = \Yii::getAlias('@webroot') . '/font';
            //Название услуги
            $name = $service->name;
            $date = date('H:i', strtotime($this->date_time)) . ' - ' . date('H:i', strtotime($this->date_time . ' +' . $this->service->duration . ' min'));

            $fontSize = round($ttfImg->getImageWidth() / mb_strlen($name)) + 5;
            $ttfImg->setFont('11143.ttf', $fontSize, "#800000", 40);

            //Шрифт для даты
            $fontSize = round($ttfImg->getImageWidth() / (mb_strlen($date) - 4)) + 5;
            $ttfImg->writeTextCenter($name, round(($fontSize) / 2) * -1 - 1);

            $ttfImg->setFont('11143.ttf', $fontSize, "#800000", 40);
            $ttfImg->writeTextCenter($date, round(($fontSize) / 2) + 1);

            //Сохраняем в базу картинку
            $this->image = $ttfImg->getImageString();
            return $this->image !== false;
        }
        $this->addError('image', 'Не удалось определить услугу.');
        return false;
    }

    public function checkDate() {
        $count = Reserve::find()
                ->where(['>=', 'date_time', $this->date_time])
                ->andWhere(['<=', 'date_time', date('Y-m-d H:i:s', strtotime($this->date_time . ' +' . $this->service->duration . ' min'))])
                ->count();
        if ($count > 0) {
            $this->addError('date_time', 'В данное время запись невозможна. Пересечение с другими записями.');
            return false;
        }

        if ((int) date('G', strtotime($this->date_time)) < 9) {
            $this->addError('date_time', 'В данное время запись невозможна. Мастер работает с 9:00.');
            return false;
        }

        if ((int) date('G', strtotime($this->date_time)) > 21) {
            $this->addError('date_time', 'В данное время запись невозможна. Мастер работает до 21:00.');
            return false;
        }

        if (date('H:i', strtotime($this->date_time . ' +' . $this->service->duration . ' min')) > date('H:i', strtotime('21:00'))) {
            $this->addError('date_time', 'В данное время запись невозможна. Мастер не успеет выполнить услугу, рабочий день до 21.');
            return false;
        }

        $sectors = Sector::find()->all();
        $time = Helper::getTime();
        foreach ($sectors as $sector) {
            if (date('H:i', strtotime($time . ' +' . $sector->hour . ' hours')) <= date('H:i', strtotime($this->date_time)) && date('H:i', strtotime($time . ' +' . $sector->hour . ' hours +' . $sector->period_min . ' min')) >= date('H:i', strtotime($this->date_time))) {
                $this->addError('date_time', 'Отказа бронирования, сектор ' . $sector->name);
                return false;
            }
        }

        return true;
    }

    public function validate($attributeNames = null, $clearErrors = true) {
        $validate = parent::validate($attributeNames, $clearErrors);
        return $validate && $this->checkDate() && $this->writeText();
    }

    //Получить услугу на которую зарезервировались
    public function getService() {
        return $this->hasOne(Service::className(), ['id' => 'service_id']);
    }

    //Получить список услуг
    public function getServices() {
        return Service::find()->all();
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'service_id' => 'Услуга',
            'date_time' => 'Дата и время',
            'image' => 'Изображение',
        ];
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Service;
use app\models\Reserve;
use app\models\Sector;
use yii\data\ActiveDataProvider;

class SiteController extends Controller {

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex() {
        $service = new Service();
        $reserve = new Reserve();

        if ($service->load(Yii::$app->request->post()) && $service->upload() && $service->save()) {
            $service = new Service();
        }

        if ($reserve->load(Yii::$app->request->post()) && $reserve->save()) {
            $reserve = new Reserve();
        }

        $list = new ActiveDataProvider([
            'query' => Reserve::find(),
        ]);

        return $this->render('index', [
                    'service' => $service,
                    'reserve' => $reserve,
                    'list' => $list,
        ]);
    }

    public function actionImage($id) {
        $reserve = Reserve::findOne($id);
        if (isset($reserve)) {
            header("Content-type: image/jpeg");
            echo $reserve->image;
        } else {
            echo 'Картинки не существует';
        }
    }

    public function actionDate() {
        $session = Yii::$app->session;
        if ($session->has('dateTime')) {
            $dateShow = date('h:i', strtotime($session->get('dateTime') . ' +1 min'));
            $session->set('dateTime', $dateShow);
        }
        return $this->renderAjax('_formDate');
    }
	
	public function actionSector($id) {
        // Нужно бы попровить место
        $model = Sector::findOne($id);

        if (isset($model) && $model->load(Yii::$app->request->post()) && $model->save()) {
            $session = Yii::$app->session;
            $sectors = Sector::find()->all();
            $session->set('sectors', $sectors);
            
            return $this->renderAjax('_sector', [
                        'model' => $model,
            ]);
        }
    }
}

views/site/_formDate.php
<?php

use yii\widgets\Pjax;
use yii\bootstrap\Html;
use app\helper\Helper;
use yii\bootstrap\Modal;

$sectors = Helper::getSectors();
$time = Helper::getTime();
?>


<?php
$script = <<< JS
$(document).ready(function() {
    setInterval(function(){  $("#refreshButton").click();}, 1000);
});
JS;
$this->registerJs($script);
?>

<?php Pjax::begin(['id' => 'formDate', 'enablePushState' => false]); ?>
<?= Html::a("Обновить", ['site/date'], ['id' => 'refreshButton', 'class' => 'hidden']); ?>
<h3 class="text-center">Сейчас: <?= $time ?></h3>

<div class="row">
    <?php if (isset($sectors) && is_array($sectors)): ?>
        <h4 class="text-center">Сектора отказа</h4>
        <?php foreach ($sectors as $sector): ?>
            <div class="col-xs-6 text-center">
                <h4><?= $sector->name ?> : <?= $sector->getStart($time) ?> - <?= $sector->getEnd($time) ?></h4>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
<?php Pjax::end(); ?>

<div class="row">
    <?php if (isset($sectors) && is_array($sectors)): ?>
        <h4 class="text-center">
            <button type="button" class="btn btn-info" data-toggle="modal" data-target="#modalSectorsEdit">Редактирование секторов</button>
        </h4>
        <?php
        Modal::begin([
            'header' => '<h3 class="text-center">Редактирование секторов</h2>',
            'id' => 'modalSectorsEdit'
        ]);
        ?>
        <div class="row">
            <?php foreach ($sectors as $sector): ?>
                <div class="col-xs-6">
                    <?=
                    $this->render('_sector', [
                        'model' => $sector,
                    ])
                    ?>
                </div>
            <?php endforeach; ?>
        </div>
        <?php Modal::end(); ?>

    <?php endif; ?>
</div>

views/site/_reserve.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model app\models\Reserve */
/* @var $form yii\widgets\ActiveForm */
?>

<?php
$this->registerJs(
        '$("document").ready(function(){
            $("#reserveForm").on("pjax:end", function() {
            $.pjax.reload({container:"#reserveList"});  //Reload GridView
        });
    });'
);
?>

<div class="reserve-form">
    <?php Pjax::begin(['id' => 'reserveForm']) ?>
    <?php
    $form = ActiveForm::begin([
                'options' => [
                    'data-pjax' => true,
                ]
    ]);
    ?>

    <?= $form->field($model, 'service_id')->dropDownList(ArrayHelper::map($model->services, 'id', 'name')) ?>

    <?=
    $form->field($model, 'date_time')->widget(
            'trntv\yii\datetime\DateTimeWidget', [
        'phpDatetimeFormat' => 'dd/MM/yyyy HH:mm:ss',
        'momentDatetimeFormat' => 'YYYY-MM-DD HH:mm'
            ]
    );
    ?>

    <?= $form->errorSummary($model) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
    <?php Pjax::end(); ?>
</div>

views/site/_sector.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model app\models\Sector */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="sector-form">
    <?php Pjax::begin(['enablePushState' => false, 'id' => 'sector_'.uniqid()]); ?>
    <?php
    $form = ActiveForm::begin([
                'action' => ['/site/sector', 'id' => $model->id],
                'id' => 'sectorForm_'.uniqid(),
                'options' => [
                    'data-pjax' => true,
                ]
    ]);
    ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'hour')->textInput() ?>

    <?= $form->field($model, 'period_min')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Обновить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
    <?php Pjax::end(); ?>
</div>

views/site/_service.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model app\models\Service */
/* @var $form yii\widgets\ActiveForm */
?>

<?php
$this->registerJs(
        '$("document").ready(function(){
            $("#serviceForm").on("pjax:end", function() {
            $.pjax.reload({container:"#reserveForm"});  //Reload GridView
        });
    });'
);
?>

<div class="service-form">
    <?php Pjax::begin(['id' => 'serviceForm']) ?>
    <?php
    $form = ActiveForm::begin([
                'options' => [
                    'data-pjax' => true,
                ]
    ]);
    ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'duration')->textInput() ?>

    <?= $form->field($model, 'upload')->fileInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?> 
    <?php Pjax::end();  ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use yii\grid\GridView;
use yii\bootstrap\Html;
use yii\helpers\Url;
use yii\widgets\Pjax
?>
<div class="row">
    <h1 class="text-center">Запись к Канадскому Автослесарю</h1>
</div>
<div class="row">
    <div class="col-xs-12">
        <?=
        $this->render('_formDate')
        ?>
    </div>
</div>
<div class="row">
    <div class="col-xs-6">
        <h2 class="text-center">Добавить услугу</h2>
        <?=
        $this->render('_service', [
            'model' => $service,
        ])
        ?>
    </div>
    <div class="col-xs-6">
        <h2 class="text-center">Записаться</h2>
        <?=
        $this->render('_reserve', [
            'model' => $reserve,
        ])
        ?>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <h2 class="text-center">Список забронированных</h2>
        <?php if (isset($list)): ?>
            <?php Pjax::begin(['id' => 'reserveList', 'enablePushState' => false]) ?>
            <?=
            GridView::widget([
                'dataProvider' => $list,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                    [
                        'label' => 'Название услуги',
                        'attribute' => 'service_id',
                        'content' => function($data) {
                            return $data->service->name;
                        }
                    ],
                    [
                        'label' => 'Дата и время регистрации',
                        'attribute' => 'date_time',
                    ],
                    [
                        'label' => 'Картинка',
                        'format' => 'raw',
                        'value' => function($data) {
                            return Html::a(
                                            'Перейти', Url::to(['site/image', 'id' => $data->id]), [
                                        'target' => '_blank',
                                        'data-pjax' => '0'
                                            ]
                            );
                        }
                            ],
                        ],
                    ]);
                    ?>
                    <?php Pjax::end(); ?>
                <?php endif; ?>
    </div>
</div>